spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/volvo
    username: volvo_admin
    password: 123456
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG